config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  #home es a a que vista predeterminada mandara al abrir la página. Vamos a testear static_pages
  #get 'static_pages/home' Esta la comento para recordar que estuvo ahí antes

  get '/help',  to: 'static_pages#help' # , as :'helf'
                                          # ^ Como hacer esto? y que funcione?
  get '/about', to: 'static_pages#about'
  
  get '/contact', to: 'static_pages#contact'
  #Si comento la siguiente linea, compruebo los ejercicios de la sección 5.4.2
  get  '/signup',  to: 'users#new'
  
  

  # root 'application#hello'

   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true,  length: {maximum: 50 } # Comprueba presencia y lengitud junto los otros test
  #Este permite poner más de un punto después de la arroba
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #Este no
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
                    length: {maximum: 255 } , 
                    format: {with: VALID_EMAIL_REGEX} ,
                    uniqueness: {case_sensitive: false}
                    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   # Returns fu tite on a per-page basis / Devuelve e titulo completo en base a un titulo por página
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    El <a href="http://www.railstutorial.org/">Tutorial de Ruby on Rails,</a>
    por <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca de", about_path %></li>
      <li><%= link_to "Contacto",  contact_path %></li>
      <li><a href="http://news.railstutorial.org/">Noticias</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Ayuda",  help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <!--Lineas default del rails fuera-->
    <%= render 'layouts/rails_default' %>
    <!--El "Si usa explorer9 o menos fuera del cuac-->
    <%= render 'layouts/shim' %>
  </head>

  <body> 
    <!--El header va fuera-->
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Para contactar con os autores puedes ir a
  <a href="http://www.railstutorial.org/help">página de ayuda del tutorial de Ruby on Rails</a>.
  Si no, también te dejamos accesible  de
  <a href="admin@railstutorial.org"><em>la dirección de email del autor  </em> del libro</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Consigue ayuda del tutorial de RoR en la
  <a href="http://www.railstutorial.org/help">página de ayuda del tutorial de Rails</a>.
  Para conseguir ayuda de esta aplicación consulta 
  <a href="http://www.railstutorial.org/book"><em>el Tutorial de Ruby on Rails </em></a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenido a Sample App</h1>
  <h2>
    Esta es la página principal para la app de prueba 
    <a href="http://www.railstutorial.org/">tutorial de Ruby on Rails </a>
  </h2>
    <%= link_to "¡Registrate ahora!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>
<%#= image_tag("kitten.jpg", alt: "Kitten") %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Registrate</h1>
<p>Esta será la página de registro para nuevos usuarios</p>